params:
        - name: magic
          type: switch
          val_range: [true, false]

        - name: mana
          type: real
          val_range: [0,10]

        - name: level
          type: integer
          val_range: [0,10]

        - name: power
          type: ordinal
          val_range: [1,2,4,8,16,32,64,128] 

        - name: creature
          type: categorical
          val_range: [dwarf, halfling, gold_golem, mage, naga,genie, dragon_golem, titan]


        - name: order
          type: permutation
          val_range: [[1,1,1,1,1],[10,10,10,10,10]]

        