params:
        - name: magic
          type: switch

        - name: mana
          type: real
          val_range: [0,1]

        - name: level
          type: integer
          val_range: [0,100]

        - name: power
          type: ordinal
          val_range: [1,128] #TODO: assert log2(x) is an integer

        - name: creature
          type: categorical
          val_range: [dwarf, halfling, gold_golem, mage, naga,genie, dragon_golem, titan]


        - name: order
          type: permutation
          val_range: [1,5]
          min_length: 1
          max_length: 5

independent_groups:
        - [magic, mana, level]
        - [power, creature]
        - [order]